function createfigure(XData1, YData1, YData2)
%CREATEFIGURE(XData1, YData1, YData2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
 
%  Auto-generated by MATLAB on 24-Oct-2023 20:25:08
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Magnitude Response (dB)');
 
% Create axes
axes1 = axes('Tag','fvtool_axes_1','Parent',figure1,...
'Position',[0.13 0.11 0.755625 0.815]);
 
% Create line
line(XData1,YData1,'Tag','magnitude_line','Parent',axes1,...
'Color',[0 0.447 0.741]);
 
% Create line
line(XData1,YData2,'Tag','magnitude_line','Parent',axes1,...
'Color',[0.85 0.325 0.098]);
 
% Create ylabel
ylabel('Magnitude (dB)');
 
% Create xlabel
xlabel('Normalized Frequency (\times\pi rad/sample)');
 
% Create title
title('Magnitude Response (dB)');
 
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.9998779296875]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-88.409081305201 74.4613333005427]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create axes
axes2 = axes('Tag','fvtool_axes_2','Parent',figure1,...
'Position',[0.13 0.11 0.755625 0.815]);
axis off
 
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 0.9998779296875]);
box(axes2,'on');
